name: PlatformIO CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Copy custom board files
        run: |
          mkdir -p ~/.platformio/platforms/ststm32/boards/
          cp -R ./boards/* ~/.platformio/platforms/ststm32/boards/

    - name: Build
      run: pio run
