name: CI

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  packages: write
  pull-requests: write
  contents: write
  issues: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          cache: pnpm

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # TODO: run linter
      # TODO: run tests

      - name: Build
        env:
          MQTT_PORT: "1883"
          MQTT_SERVER: "192.168.0.1"
          MQTT_USERNAME: "test"
          MQTT_PASSWORD: "test"
          PIN_HASH: "test"
          PIN_KEY: "test"
          WIFI_SSID: "test"
          WIFI_PASSWORD: "test"
          TOUCH_FORCE_CALIBRATION: 1
        run: pio run

      - name: Create build
        if: github.ref == 'refs/heads/main'
        run: tar -cvf esp32-cyd.tar .pio/build

      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
